{{ if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1/VerticalPodAutoscaler" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ingress-allowlist-controller
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    kind: Deployment
    name: {{ .Release.Name }}
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Chart.Name }}
      minAllowed:
        cpu: 100m
        memory: 128M
      maxAllowed:
        memory: "1Gi"
        cpu: "1"
{{ end }}
