{{ if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1/VerticalPodAutoscaler" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ingress-allowlist-controller
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    kind: Deployment
    name: {{ .Release.Name }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode }}
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Chart.Name }}
    {{- with .Values.vpa.containerPolicy }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
{{ end }}
